# Generated by Django 4.1.3 on 2023-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejorado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca_del_Carro', models.CharField(max_length=100)),
                ('Modelo_del_Carro', models.CharField(max_length=100)),
                ('Especificaciones_del_Modelo', models.TextField(max_length=3000)),
                ('publicado_el', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
