# Generated by Django 4.1.3 on 2023-01-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_del_carro', models.CharField(max_length=100)),
                ('modelos_del_carro', models.CharField(max_length=200)),
                ('color_del_carro', models.CharField(max_length=20)),
            ],
        ),
    ]
